/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tareaarchivos;

import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author camilo
 */
public class archivosForm extends javax.swing.JFrame {
        manejoArchivos arch = new manejoArchivos();
       static JFileChooser choose = new JFileChooser();
        public String name;
        static File arc;
    /**
     * Creates new form archivosForm
     */
    public archivosForm() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardarArchivo = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtPane = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnTable = new javax.swing.JButton();
        SalidaSE = new javax.swing.JButton();
        UpperLower = new javax.swing.JButton();
        Unir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevoArch = new javax.swing.JMenuItem();
        abrirArch = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Archivos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardarArchivo.setText("Guardar");
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(guardarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, -1));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtPane.setViewportView(txtArea);

        getContentPane().add(txtPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 638, 391));

        btnTable.setText("Tabla!");
        btnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableActionPerformed(evt);
            }
        });
        getContentPane().add(btnTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, -1));

        SalidaSE.setText("Quitar espacios");
        SalidaSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaSEActionPerformed(evt);
            }
        });
        getContentPane().add(SalidaSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        UpperLower.setText("Cambiar Case");
        UpperLower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpperLowerActionPerformed(evt);
            }
        });
        getContentPane().add(UpperLower, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        Unir.setText("Unir Archivos");
        Unir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnirActionPerformed(evt);
            }
        });
        getContentPane().add(Unir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jMenu1.setText("Archivo");

        nuevoArch.setText("Nuevo");
        nuevoArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoArchActionPerformed(evt);
            }
        });
        jMenu1.add(nuevoArch);

        abrirArch.setText("Abrir");
        abrirArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchActionPerformed(evt);
            }
        });
        jMenu1.add(abrirArch);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        
        String text = txtArea.getText();
       
        if(!arch.setTexto(text,arc)){
            JOptionPane.showMessageDialog(null, "No se ha creado el archivo!");
            nuevoArchActionPerformed(evt);
            arch.setTexto(text,arc);
        }else{
            JOptionPane.showMessageDialog(null, "Archivo guardado exitosamente!");
        }
        
        txtArea.requestFocus();
        txtArea.setText("");
        
    }//GEN-LAST:event_guardarArchivoActionPerformed

    private void nuevoArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoArchActionPerformed
       try {
     
        if(choose.showDialog(null, "Crear archivo")== JFileChooser.APPROVE_OPTION){
             arc = choose.getSelectedFile();
                    arch.crearArchivoED(arc);
                
                this.setTitle(arc.getName());}
          // System.out.println(arc.getName());
          
            } catch (Exception ex) {
                Logger.getLogger(archivosForm.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_nuevoArchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        arch.borrar(arc);
        setTitle("Sin Archivo");
        arc = null;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void abrirArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchActionPerformed
        try {
         if(choose.showDialog(null, "Abrir archivo")== JFileChooser.APPROVE_OPTION){
             arc = choose.getSelectedFile();
                    
           
        ArrayList txt = new ArrayList<>();
        txt = arch.getTexto(arc);
        
              for(int j = 0;j< txt.size();j++){
            txtArea.append(txt.get(j).toString()+"\n");
        }
         }       
            } catch (Exception ex) {
                Logger.getLogger(archivosForm.class.getName()).log(Level.SEVERE, null, ex);
            }
         
      
        setTitle(arc.getName());
    }//GEN-LAST:event_abrirArchActionPerformed

    private void btnTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableActionPerformed
      
        if(arc !=null){new ArchivosED(arc).setVisible(true);}
        
    }//GEN-LAST:event_btnTableActionPerformed

    private void SalidaSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaSEActionPerformed
      try {
         if(choose.showDialog(null, "Abrir archivo")== JFileChooser.APPROVE_OPTION){
             arc = choose.getSelectedFile();
                    
           
        ArrayList txt = new ArrayList<>();
        txt = arch.getTextoSE(arc);
        
              for(int j = 0;j< txt.size();j++){
            txtArea.append(txt.get(j).toString());
        }
         }       
            } catch (Exception ex) {
                Logger.getLogger(archivosForm.class.getName()).log(Level.SEVERE, null, ex);
            }
         
      
        setTitle(arc.getName());
    }//GEN-LAST:event_SalidaSEActionPerformed

    private void UpperLowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpperLowerActionPerformed
       try {
         if(choose.showDialog(null, "Abrir archivo")== JFileChooser.APPROVE_OPTION){
             arc = choose.getSelectedFile();
                    
           
        ArrayList txt = new ArrayList<>();
        txt = arch.getTextoUpperCase(arc);
        
              for(int j = 0;j< txt.size();j++){
            txtArea.append(txt.get(j).toString()+"");
        }
         }       
            } catch (Exception ex) {
                Logger.getLogger(archivosForm.class.getName()).log(Level.SEVERE, null, ex);
            }
         
      
        setTitle(arc.getName());
    }//GEN-LAST:event_UpperLowerActionPerformed

    private void UnirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnirActionPerformed
       File archivo1, archivo2;
        try {
            choose.showDialog(null,"Crear archivo como resultado de la union");
            arc = choose.getSelectedFile();
             choose.showDialog(null,"Abrir primer archivo");
            archivo2 = choose.getSelectedFile();
         if(choose.showDialog(null, "Abrir segundo archivo")== JFileChooser.APPROVE_OPTION){
             archivo1 = choose.getSelectedFile();
             arch.unitTxt(archivo2,archivo1,arc);
           
        ArrayList txt = new ArrayList<>();
        txt = arch.getTexto(arc);
        
              for(int j = 0;j< txt.size();j++){
            txtArea.append(txt.get(j).toString()+ "\n");
        }
         }       
            } catch (Exception ex) {
                Logger.getLogger(archivosForm.class.getName()).log(Level.SEVERE, null, ex);
            }
         
      
        setTitle(arc.getName());
    }//GEN-LAST:event_UnirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(archivosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(archivosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(archivosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(archivosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new archivosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalidaSE;
    private javax.swing.JButton Unir;
    private javax.swing.JButton UpperLower;
    private javax.swing.JMenuItem abrirArch;
    private javax.swing.JButton btnTable;
    private javax.swing.JButton guardarArchivo;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem nuevoArch;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JScrollPane txtPane;
    // End of variables declaration//GEN-END:variables
}
